

#define PORT_PREFIX "\\\\.\\"
#define CONVAYORBELT_ON_DATA "ON"
#define CONVAYORBELT_OFF_DATA "OFF"
#define MAXIMUM_COMMUNICATION_COUNT 20
#define DATA_LENGTH 255
#define SYNC_TIME 1000

#define DATASTORE_PATH "./log.txt"

#define OBJECT_DETECTION "OBJECTDETECTION"


//커스텀 메시지
#define ON_CONNECT_COMPLETE_MESSAGE WM_USER + 150